#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : cppzmq
Version  : 4.3.0
Release  : 2
URL      : https://github.com/zeromq/cppzmq/archive/v4.3.0.tar.gz
Source0  : https://github.com/zeromq/cppzmq/archive/v4.3.0.tar.gz
Summary  : Header-only C++ binding for libzmq (only CMake module)
Group    : Development/Tools
License  : BSD-3-Clause MIT
Requires: cppzmq-data = %{version}-%{release}
Requires: cppzmq-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : libzmq-staticdev
BuildRequires : pkg-config
BuildRequires : pkgconfig(libzmq)

%description
[![Travis-CI Status](https://img.shields.io/travis/zeromq/cppzmq/master.svg?label=Linux%20|%20OSX)](https://travis-ci.org/zeromq/cppzmq)
[![Appveyor Status](https://img.shields.io/appveyor/ci/zeromq/cppzmq/master.svg?label=Windows)](https://ci.appveyor.com/project/zeromq/cppzmq/branch/master)
[![Coverage Status](https://coveralls.io/repos/github/zeromq/cppzmq/badge.svg?branch=master)](https://coveralls.io/github/zeromq/cppzmq?branch=master)
[![License](https://img.shields.io/github/license/zeromq/cppzmq.svg)](https://github.com/zeromq/cppzmq/blob/master/LICENSE)

%package data
Summary: data components for the cppzmq package.
Group: Data

%description data
data components for the cppzmq package.


%package dev
Summary: dev components for the cppzmq package.
Group: Development
Requires: cppzmq-data = %{version}-%{release}
Provides: cppzmq-devel = %{version}-%{release}
Requires: cppzmq = %{version}-%{release}
Requires: cppzmq = %{version}-%{release}

%description dev
dev components for the cppzmq package.


%package license
Summary: license components for the cppzmq package.
Group: Default

%description license
license components for the cppzmq package.


%prep
%setup -q -n cppzmq-4.3.0
cd %{_builddir}/cppzmq-4.3.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583269324
mkdir -p clr-build
pushd clr-build
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%cmake .. -DCPPZMQ_BUILD_TESTS=OFF
make  %{?_smp_mflags}  VERBOSE=1
popd

%install
export SOURCE_DATE_EPOCH=1583269324
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/cppzmq
cp %{_builddir}/cppzmq-4.3.0/LICENSE %{buildroot}/usr/share/package-licenses/cppzmq/06c6b2191805315cbc96ae218f1edb66c17da4e3
cp %{_builddir}/cppzmq-4.3.0/external/gtest-demo/LICENSE %{buildroot}/usr/share/package-licenses/cppzmq/fcc9d9d2e18ef8e8f9dc5bba08bc9a0712144ace
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/cmake/*

%files dev
%defattr(-,root,root,-)
/usr/include/zmq.hpp
/usr/include/zmq_addon.hpp

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/cppzmq/06c6b2191805315cbc96ae218f1edb66c17da4e3
/usr/share/package-licenses/cppzmq/fcc9d9d2e18ef8e8f9dc5bba08bc9a0712144ace
